configuratioooooooooooooooooooooooooooooooooooooooon also akiyama mizuki is tuff

diff --git a/f--fetch b/f--fetch
--- a/f--fetch
+++ b/f--fetch
@@ -38,6 +38,32 @@ UNDERLINE=$(printf '\033[4m')
 
 RESET=$(printf '\033[0m')
 
+if command >/dev/null 2>&1; then
+  hascmd() {
+    command -v "$1" >/dev/null 2>&1
+  }
+else
+  if type >/dev/null 2>&1; then
+    err "Command '${UNDERLINE}command$RESET${RED}' not found! Falling back to 'type'."
+    hascmd() {
+      type "$1" >/dev/null 2>&1
+    }
+  else
+    hascmd(){
+      old_ifs=$IFS
+      IFS=:
+      for dir in $PATH; do
+        [ -x "${dir:-.}/$1" ] && {
+          IFS=$old_ifs
+          return 0
+        }
+      done
+      IFS=$old_ifs
+      return 1
+    }
+  fi
+fi
+
 if [ "$1" = "--verbose" ]; then
   err() {
     printf '%s\n' "$RED$*$RESET" >&2
@@ -46,6 +72,8 @@ if [ "$1" = "--verbose" ]; then
   log(){
     printf '%s\n' "$CYAN$*$RESET" >&2
   }
+  
+  shift
 
   log "Logging is enabled!"
 else
@@ -57,6 +85,71 @@ else
     :
   }
 fi
+
+if [ "$1" = "--gen-config" ]; then
+  shift
+  if ! [ "Mizuki$1" = "Mizuki" ]; then
+    Cfg="$1"
+    shift
+  else
+    if ! hascmd pwd; then
+      err "${UNDERLINE}pwd$RESET${RED} not found, you might need to add a config path.."
+      exit 1
+    fi
+    Cfg="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)/config"
+  fi
+
+  if ! hascmd cat; then
+    err "${UNDERLINE}cat$RESET${RED} not found, cannot create config..."
+    exit 1
+  fi
+  log "Generating config..."
+  cat >"$Cfg" <<'EOF' 
+# Default logo(trans flag)
+logo=$(
+  color "$transBLUE" "$BOX"
+  color "$transBLUE" "$BOX"
+  color "$transPINK" "$BOX"
+  color "$transPINK" "$BOX"
+  color "$transWHITE" "$BOX"
+  color "$transWHITE" "$BOX"
+  color "$transPINK" "$BOX"
+  color "$transPINK" "$BOX"
+  color "$transBLUE" "$BOX"
+  color "$transBLUE" "$BOX"
+)
+
+# Default modules list
+main() {
+  Hostname
+  Line_Break
+  OS
+  Init
+  Shell
+  Pwd
+  Terminal
+  TTY
+  Break
+  Kernel
+  Memory
+  CPU
+  GPU
+  Host
+  Uptime
+  Packages
+  TimeDate
+  Break
+  Music
+  Desktop
+  Editor
+  Visual
+  Break
+  Colors
+}
+EOF
+  log "Config generated!"
+  exit
+fi 
 
 color() {
   printf '%s%s%s\n' "$1" "$2" "$RESET"
@@ -94,31 +187,6 @@ logo=$(
   color "$transBLUE" "$BOX"
 )
 
-if command >/dev/null 2>&1; then
-  hascmd() {
-    command -v "$1" >/dev/null 2>&1
-  }
-else
-  if type >/dev/null 2>&1; then
-    err "Command '${UNDERLINE}command$RESET${RED}' not found! Falling back to 'type'."
-    hascmd() {
-      type "$1" >/dev/null 2>&1
-    }
-  else
-    hascmd(){
-      old_ifs=$IFS
-      IFS=:
-      for dir in $PATH; do
-        [ -x "${dir:-.}/$1" ] && {
-          IFS=$old_ifs
-          return 0
-        }
-      done
-      IFS=$old_ifs
-      return 1
-    }
-  fi
-fi
 
 # Use this when the entire shit is done
 print_fetch() {
@@ -859,7 +927,7 @@ Host(){
 }
 
 CheeseCakeFight(){
-    if hascmd od; then
+  if hascmd od; then
     set -- "Shinonome Ena" "Shinonome Akito"
     CheeseCake=$(( $(od -An -N4 -tu4 /dev/random) % $# + 1 ))
 
@@ -944,7 +1012,7 @@ main() {
   Break
   MyVersion
   Colors
-  CrrMoonPhrase
+  # CrrMoonPhrase
   Break
   AkiyamaMizukiIsTuff
   # Break
@@ -954,6 +1022,12 @@ main() {
   # Mizuki so tuff TransFlag module exists
   # CheeseCakeFight
 }
+
+if [ -f config ]; then
+  log "Config found! Sourcing it..."
+  . ./config
+  log "Sourced config"
+fi
 
 fetch_info="$(main)"
 
