Added darwin kernel support

diff --git a/f--fetch b/f--fetch
--- a/f--fetch
+++ b/f--fetch
@@ -80,69 +80,17 @@ EOF
     exec 3<&-
 }
 
-Hostname() {
-  if hascmd hostname; then
-    printf "$GREEN$(hostname)@$USER$RESET\n"
-  else
-    printf "${RED}Null${RESET}@$GREEN$USER$RESET\n"
-  fi
-}
-
-if [ -f /etc/os-release ]; then
-  OS() {
-    . /etc/os-release
-    printf '%-10s : %s\n' "OS" "$GREEN$PRETTY_NAME$RESET"
-  }
+if hascmd uname; then
+  OS=$(uname -s)
 else
-  OS() {
-    :
-  }
-  err "/etc/os-release not found!"
+  OS=Linux
+  err "Command 'uname' not found! Defaulting to Linux."
 fi
 
-Shell() {
-  printf '%-10s : %s\n' "Shell" "$GREEN$SHELL$RESET"
-}
-
-Terminal() {
-  printf '%-10s : %s\n' "Terminal" "$GREEN$TERM$RESET"
-}
 
 Init() {
   :
 }
-
-if hascmd readlink; then
-  if hascmd basename; then
-    if [ "$USER" = "root" ]; then
-      Init() {
-        init=$(readlink -f /proc/1/exe)
-        printf '%-10s : %s\n' "Init" "$GREEN$(basename "$init")$RESET"
-      }
-    fi
-  else
-    err "Command 'basename' not found!"
-  fi
-else
-  err "Comamnd 'readlink' not found!"
-fi
-
-if hascmd uname;then
-  Kernel() {
-    printf '%-10s : %s\n' "Kernel" "$GREEN$(uname -sv)$RESET"
-    Arch="$(uname -i)"
-    if [ "$Arch" = "unknown" ];then
-      printf '%-10s : %s\n' "Arch" "$GREEN$(uname -m)$RESET"
-    else
-      printf '%-10s : %s\n' "Arch" "$GREEN$Arch$RESET"
-    fi
-  }
-else
-  Kernel() {
-    printf '%-10s : %s\n' "Kernel" "$GREEN$(cat /proc/version)$RESET"
-  }
-  err "Comamnd 'uname' not found! Using the good old /proc."
-fi
 
 Memory() {
   :
@@ -155,32 +103,197 @@ CPU() {
 Uptime() {
   :
 }
-if hascmd awk;then
-  Memory() {
-    MemTotal="$(awk '/^MemTotal:/ { print $2 }' /proc/meminfo)"
-    MemMiB=$((MemTotal / 1024))
-    printf '%-10s : %s ' "Memory" "$GREEN${MemMiB}MiB"
-    if [ -f /proc/swaps ]; then
-      printf '%s' "$(awk 'NR > 1 { printf "%s%s : %sMiB", (NR > 2 ? ", " : "("), $1, $3/1024 } END { print ")" }' /proc/swaps)"
-    fi
-    printf '%s \n' "$RESET"
-  }
-  
-  CPU() {
-    CPU="$(awk -F: '/^model name/ {gsub(/^[ \t]+/, "", $2); print $2; exit}' /proc/cpuinfo)"
-    if [ "x$CPU" = "x" ];then
-      CPU=idk
-    fi
-    printf '%-10s : %s\n' "CPU" "$GREEN$CPU$RESET"
-  }
 
-  Uptime() {
-    printf '%-10s : %s\n' "Uptime" "$GREEN$(awk '{printf "%d days, %02d:%02d:%02d\n", $1/86400, $1/3600%24, $1/60%60, $1%60}' /proc/uptime)$RESET"
-  }
+Music() {
+  :
+}
 
-else
-  err "WHAT THE FUCK THERE'S NO awk???"
+if [ "$OS" = "Darwin" ]; then
+  if ! hascmd sysctl; then
+    err "Command 'sysctl' not found! Aborting fetch."
+    exit 1
+  fi
 fi
+
+case "$OS" in
+  Darwin)
+    Hostname() {
+      printf "$GREEN$(sysctl -n kern.hostname)@$USER$RESET\n"
+    }
+    
+    Init(){
+      printf '%-10s : %s\n' "Init" "${GREEN}Launchd$RESET"
+
+    }
+
+    Desktop() {
+      printf '%-10s : %s\n' "Desktop" "${GREEN}Springboard$RESET"
+    }
+
+    OS() {
+      case "$(sysctl -n hw.product)" in
+        iPhone*)
+          DarwinOS=iOS
+          ;;
+        iPad*)
+          DarwinOS=iPadOS
+          ;;
+        *)
+          DarwinOS=macOS
+        ;;
+      esac
+      printf '%-10s : %s %s\n' "OS" "$GREEN$DarwinOS" "$(sysctl -n kern.osproductversion)$RESET"
+    }
+    
+    Memory() {
+      MemBytes="$(sysctl -n hw.memsize)"
+      MemMiB=$((MemBytes / 1024 / 1024))
+      printf '%-10s : %s (Swap : %s)\n' "Memory" "$GREEN${MemMiB}MiB" "$(sysctl -n vm.swapusage)$RESET"
+    }
+
+    CPU() {
+      CPU="$(sysctl -n machdep.cpu.brand_string)"
+      Cores="$(sysctl -n machdep.cpu.core_count)"
+      printf '%-10s : %s\n' "CPU" "$GREEN$CPU (${Cores} cores)$RESET"
+    }
+
+    if hascmd awk; then
+      Uptime() {
+        Boot="$(sysctl -n kern.boottime | awk -F'[ =,}]+' '{print $3}')"
+        Now="$(date +%s)"
+        Uptime=$((Now - Boot))
+
+       printf '%-10s : %s\n' "Uptime" \
+        "$GREEN$((Uptime / 86400)) days, $(printf '%02d:%02d:%02d' \
+        "$((Uptime / 3600 % 24))" \
+        "$((Uptime / 60 % 60))" \
+        "$((Uptime % 60))")$RESET"
+      }
+    else
+      err "What kind of apple produc is this that have to awk?"
+    fi
+    
+    ;;
+
+  Linux)
+    Hostname() {
+      if hascmd hostname; then
+        printf "$GREEN$(hostname)@$USER$RESET\n"
+      else
+        printf "${RED}Null${RESET}@$GREEN$USER$RESET\n"
+      fi
+    }
+
+    if hascmd readlink; then
+      if hascmd basename; then
+        if [ "$USER" = "root" ]; then
+          Init() {
+            init=$(readlink -f /proc/1/exe)
+            printf '%-10s : %s\n' "Init" "$GREEN$(basename "$init")$RESET"
+          }
+        fi
+      else
+        err "Command 'basename' not found!"
+      fi
+    else
+      err "Comamnd 'readlink' not found!"
+    fi
+
+    if [ -f /etc/os-release ]; then
+      OS() {
+        . /etc/os-release
+        printf '%-10s : %s\n' "OS" "$GREEN$PRETTY_NAME$RESET"
+      }
+    else
+      OS() {
+        :
+      }
+      err "/etc/os-release not found!"
+    fi
+
+    if hascmd awk;then
+      Memory() {
+        MemTotal="$(awk '/^MemTotal:/ { print $2 }' /proc/meminfo)"
+        MemMiB=$((MemTotal / 1024))
+        printf '%-10s : %s ' "Memory" "$GREEN${MemMiB}MiB"
+        if [ -f /proc/swaps ]; then
+          printf '%s' "$(awk 'NR > 1 { printf "%s%s : %sMiB", (NR > 2 ? ", " : "("), $1, $3/1024 } END { print ")" }' /proc/swaps)"
+        fi
+        printf '%s \n' "$RESET"
+        }
+  
+      CPU() {
+        CPU="$(awk -F: '/^model name/ {gsub(/^[ \t]+/, "", $2); print $2; exit}' /proc/cpuinfo)"
+        if [ "x$CPU" = "x" ];then
+          CPU=idk
+        fi
+        printf '%-10s : %s\n' "CPU" "$GREEN$CPU$RESET"
+      }
+
+      Uptime() {
+        printf '%-10s : %s\n' "Uptime" "$GREEN$(awk '{printf "%d days, %02d:%02d:%02d\n", $1/86400, $1/3600%24, $1/60%60, $1%60}' /proc/uptime)$RESET"
+      }
+
+    else
+      err "WHAT THE FUCK THERE'S NO awk???"
+    fi
+
+    Desktop() {
+      if [ "x$DESKTOP_SESSION" != "x" ]; then
+        printf '%-10s : %s\n' "Desktop" "$GREEN$DESKTOP_SESSION$RESET"
+      fi
+    }
+
+    if hascmd playerctl; then
+      Music() {
+        title=$(playerctl metadata xesam:title)
+          if [ "x$title" != "x" ];then
+            printf '%-10s : %s(%s)\n%s' \
+              "Music" "$GREEN$title" "$(playerctl metadata xesam:artist)" "$RESET"
+        fi
+      }
+    else
+      err "Command 'playerctl' not found! No music information :( "
+    fi
+    ;;
+esac
+
+Shell() {
+  printf '%-10s : %s\n' "Shell" "$GREEN$SHELL$RESET"
+}
+
+Terminal() {
+  printf '%-10s : %s\n' "Terminal" "$GREEN$TERM$RESET"
+}
+
+if hascmd uname;then
+  Kernel() {
+    printf '%-10s : %s\n' "Kernel" "$GREEN$(uname -sr)$RESET"
+    Arch="$(uname -p)"
+    if [ "$Arch" = "unknown" ];then
+      printf '%-10s : %s\n' "Arch" "$GREEN$(uname -m)$RESET"
+    else
+      printf '%-10s : %s\n' "Arch" "$GREEN$Arch$RESET"
+    fi
+  }
+else
+  case "$OS" in
+    Linux)
+      err "Comamnd 'uname' not found! Using the good old /proc."
+      Kernel() {
+        printf '%-10s : %s\n' "Kernel" "$GREEN$(cat /proc/version)$RESET"
+      }
+      ;;
+    Darwin)
+      err "Comamnd 'uname' not found! Using the good old sysctl."
+      Kernel() {
+        printf '%-10s : %s\n' "Kernel" "$GREEN$(sysctl -n kern.version)$RESET"
+      }
+      ;;
+  esac
+
+fi
+
 
 Packages() {
   :
@@ -221,11 +334,7 @@ else
   err "Command 'wc' not found!"
 fi
 
-Desktop() {
-  if [ "x$DESKTOP_SESSION" != "x" ]; then
-    printf '%-10s : %s\n' "Desktop" "$GREEN$DESKTOP_SESSION$RESET"
-  fi
-}
+
 
 Language() {
   if [ "x$LANG" != "x" ]; then
@@ -239,21 +348,8 @@ LoadAVG() {
   fi
 }
 
-Music() {
-  :
-}
 
-if hascmd playerctl; then
-  Music() {
-    title=$(playerctl metadata xesam:title)
-    if [ "x$title" != "x" ];then
-      printf '%-10s : %s(%s)\n%s' \
-        "Music" "$GREEN$title" "$(playerctl metadata xesam:artist)" "$RESET"
-    fi
-  }
-else
-  err "Command 'playerctl' not found! No music information :( "
-fi
+
 
 Colors(){
   printf '%s███%s' "$BLACK" "$RESET"
